### ISSUE TITLE
Cannot change minibatch size

### ISSUE THREAD

**Issue by suyuzhang** [hsn-zeinali/x-vector-kaldi-tf#1]
Hi,

I changed the minibatch from 128 to 64, but when I run on ```local/tf/get_egs.sh: Generating training subset examples on disk```  this step appears the error.

```
  4 2019-01-08 18:12:57,436 [local/tf/create_tar_files.py:25 - <module> - INFO ] Starting DNN trainer to do a training iteration (train_dnn_one_iteration.py)
  5 Traceback (most recent call last):
  6   File "local/tf/create_tar_files.py", line 140, in main
  7     process_files(args)
  8   File "local/tf/create_tar_files.py", line 117, in process_files
  9     scp_file_path, feature_dim)
 10   File "/D/git/xvector-kaldi-tf/local/tf/examples_io.py", line 128, in load_ranges_info
 11     labels[minibatch_index][info[2]] = label
 12 IndexError: index 64 is out of bounds for axis 0 with size 64
```
How can I fix it?
Thank you very much!

**Comment by hsn-zeinali** [comment]
There was a problem in the "local/tf/get_egs.sh" and now it was solved. I forgot to pass minibatch size to example generation script (local/tf/create_egs.py) for validation and train_subset. I have close this issue, If there will be any similar issues, please reopen it again.
